apiVersion: triggers.tekton.dev/v1beta1 #apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: node-web-app-tt
spec:
  params: 
  - name: git-repo-url
    default: main # master
  - name: git-repo-name
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: node-web-app-pipeline-run-
    spec:
      serviceAccountName: build-bot
      pipelineRef:
        name: node-web-app-pipeline
      podTemplate:
        securityContext:
          fsGroup: 65532
      workspaces:
      - name: shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      - name: git-credentials
        secret:
          secretName: git-credentials
      - name: nexus-credentials
        secret:
          secretName: docker-credentials-secret #nexus-credentials
      params:
      - name: repo-url
        value: https://github.com/kriztobal/node-web-app.git # https://github.com/kriztobal/react-tekton-argo.git
      - name: image-reference
        value: becariodocker/react-app:1.0.1 # 192.168.162.161:8082/repository/project/test-app:1.0.1


--- 

apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: node-web-app-tb
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.url)
  - name: git-revision
    value: $(body.head_commit.id)
  - name: git-repo-name
    value: $(body.repository.name)

---

apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: node-web-app-el
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: node-web-app-tb
    template:
      name: node-web-app-tt

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-node-web-app
  namespace: node-web-project
spec:
  host: el-node-web-app.apps.roly-ocp43-cluster.roly-ocp.com
  to:
    kind: Service
    name: el-node-web-app-el
    weight: 100