apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: node-web-app-pipeline
  # namespace: node-web-project
spec:
  params: #resource:
    - name: repo-url #node-web-app-source
      type: string #git
      description: La URL desde donde se va a clonar
    - name: image-reference #node-web-app-image
      type: string #image
  workspaces:
  - name: shared-data
    description: Este espacio de trabajo contiene los archivos de repositorio clonados, por lo que pueden ser leídos por la siguiente tarea.
  - name: nexus-credentials
    description: Espacio de trabajo de mis credenciales de Docker en Nexus. 
  - name: git-credentials
    description: Espacio de trabajo de mis credenciales de Github. 
  
  tasks:
  - name: fetch-source        ##### TASK 1 CLONAR CÓDIGO FUENTE DE GITHUB
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    - name: ssh-directory
      workspace: git-credentials
    params:
    - name: url
      value: $(params.repo-url)
  - name: get-tag          ##### TASK 2 GET TAG     # CAMBIO DE PRUEBA 4
    runAfter: ["fetch-source"]
    workspaces:
    - name: source
      workspace: shared-data 
    - name: dockerconfig 
      workspace: nexus-credentials  
    taskSpec:
      steps:
        - name: obtener-tag
          image: centos # imagen con CURL comment1
          script: |
            TAG_LATEST=$(curl -u $username:$password -X GET "http://$ip/service/rest/v1/search/?repository=project" | grep version | tail -n 1 | awk -F'[^0-9]+'  '{print $4}')
            echo $TAG_LATEST
            echo " * * * * * "
            ((TAG_LATEST+=1))
            echo $TAG_LATEST
          env:
            - name: username   # SECRET 1
              valueFrom:
                secretKeyRef:
                  name: secret-tag
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: secret-tag
                  key: password
            - name: ip          # SECRET 2
              valueFrom:
                secretKeyRef:
                  name: secret-ip
                  key: password
  - name: build-push          ##### TASK 3 BUILD AND PUSH
    runAfter: ["get-tag"]
    taskRef:
      name: kaniko
    workspaces:
    - name: source
      workspace: shared-data 
    - name: dockerconfig 
      workspace: nexus-credentials
    params:   
    - name: IMAGE 
      value: $(params.image-reference)      