apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: node-web-app-tt # pipeline-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: main
  - name: gitrepositoryurl  # URL DE REPOSITORIO
    description: The git repository url
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: node-web-app-pipeline-run-
    spec:
      serviceAccountName: build-bot
      pipelineRef:
        name: node-web-app-pipeline
      podTemplate:
        securityContext:
          fsGroup: 65532
      workspaces:
      - name: shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      - name: git-credentials
        secret:
          secretName: git-credentials
      - name: nexus-credentials
        secret:
          secretName: nexus-credentials
      params:
      - name: repo-url
        value: https://github.com/kriztobal/node-web-app.git # https://github.com/kriztobal/react-tekton-argo.git
      - name: image-reference
        value: 192.168.162.161:8082/repository/project/test-app:1.0.7
# Comentario de prueba MAIN con tag 1.0.7
--- 

apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: node-web-app-tb # pipeline-binding
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: gitrepositoryurl
    value: $(body.repository.url)
  - name: contenttype
    value: $(header.Content-Type)

# apiVersion: tekton.dev/v1alpha1
# kind: TriggerBinding
# metadata:
#   name: node-web-app-tb
# spec:
#   params:
#   - name: git-repo-url
#     value: $(body.repository.url)
#   - name: git-revision
#     value: $(body.head_commit.id)
#   - name: git-repo-name
#     value: $(body.repository.name)

---

# apiVersion: triggers.tekton.dev/v1beta1
# kind: Trigger
# metadata:
#   name: trigger
# spec:
#   interceptors:
#     - ref:
#         name: "cel"
#       params:
#         - name: "filter"
#           value: "header.match('X-GitHub-Event', 'pull_request')"
#         - name: "overlays"
#           value:
#             - key: extensions.truncated_sha
#               expression: "body.pull_request.head.sha.truncate(7)"
#   bindings:
#   - ref: node-web-app-tb # pipeline-binding
#   template:
#     ref: node-web-app-tt # pipeline-template

---

apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: node-web-app-el # eventlistener
spec:
  serviceAccountName: tekton-triggers-example-sa # trigger-sa # pipeline
  triggers:
    - name: trigger
      # interceptors:
      #   - github:
      #       eventTypes: ["pull_request"]
      bindings:
        - ref: node-web-app-tb # pipeline-binding
      template:
        ref: node-web-app-tt # pipeline-template
